spring:
  profiles:
    active: local

  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 30MB

  jpa:
    properties:
      hibernate:
        highlight_sql: 'true'
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: debug
      springframework:
        transaction:
          interceptor: trace
        security:
          nodeValue: debug
          web: trace

---

# local 데이터베이스 설정

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_user
    username: root
    password:

---

# prod 데이터베이스 설정

#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}



